version: '3.9'

services:
    tgbot:
        image: ${DOCKER_REPO_URL}${CI_PROJECT_NAME}/tgbot:${IMAGE_TAG}
        hostname: '{{index .Service.Labels "com.docker.stack.namespace"}}.{{.Task.Slot}}.{{index .Service.Labels "ru.seals.service"}}'
        #deploy:
        #  replicas: ${TGBOT_REPLICAS}
        #  update_config:
        #    parallelism: 1
        #    delay: 10s
        #    order: stop-first
        #  restart_policy:
        #    condition: any
        #    delay: 10s
        #
        environment:
            BOT_TOKEN: tgbot-bot-token
            API_KEY: tgbot-api-key
            TABLE_ID: tgbot-table_id
        secrets:
            - tgbot-bot-token
            - tgbot-api-key
            - tgbot-table_id
        logging:
            driver: 'json-file'
            options:
                max-size: '10m'

secrets:
    tgbot-bot-token:
        external: true
    tgbot-api-key:
        external: true
    tgbot-table_id:
        external: true

networks:
    default:
        name: dripid-network
        external: true
